<script setup lang="ts">
import { onMounted } from 'vue';
import { usePrisma } from '@/composables/use-prisma';

const { svgContent, data, loading, loadDiagram, exportSvg, exportPng } = usePrisma();

onMounted(loadDiagram);
</script>

<template>
  <div class="prisma-view">
    <div class="prisma-view__header">
      <h1>PRISMA 2020 Flow Diagram</h1>
      <div class="prisma-view__actions">
        <button class="btn btn--secondary" @click="exportSvg">
          <span class="material-symbols-outlined btn__icon">download</span>
          Export SVG
        </button>
        <button class="btn btn--secondary" @click="exportPng">
          <span class="material-symbols-outlined btn__icon">download</span>
          Export PNG
        </button>
        <button class="btn btn--primary" :disabled="loading" @click="loadDiagram">Refresh</button>
      </div>
    </div>

    <!-- eslint-disable-next-line vue/no-v-html -- SVG content generated by trusted Rust backend -->
    <div v-if="svgContent" class="prisma-view__diagram" v-html="svgContent" />

    <div v-if="data" class="prisma-view__summary">
      <span>
        {{ data.recordsIdentified }} identified -> {{ data.duplicatesRemoved }} duplicates removed
        -> {{ data.recordsScreened }} screened -> {{ data.recordsExcluded }} excluded ->
        {{ data.studiesIncluded }} included
      </span>
    </div>

    <div v-if="data && data.exclusionReasons.length > 0" class="prisma-view__reasons">
      <h2>Exclusion Reasons</h2>
      <ul>
        <li v-for="reason in data.exclusionReasons" :key="reason.criterionId">
          {{ reason.criterionText }} (n={{ reason.count }})
        </li>
      </ul>
    </div>
  </div>
</template>

<style scoped>
.prisma-view {
  padding: var(--container-padding);
}

@media (max-width: 767px) {
  .prisma-view {
    padding: var(--container-padding-sm);
  }

  .prisma-view__header {
    flex-direction: column;
    gap: var(--space-3, 12px);
    align-items: flex-start;
  }

  .prisma-view__actions {
    flex-wrap: wrap;
  }

  .prisma-view__diagram {
    overflow-x: auto;
  }
}
.prisma-view__header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: var(--space-6, 24px);
}
.prisma-view__header h1 {
  font-size: var(--font-size-display, 24px);
  font-weight: var(--font-weight-semibold, 600);
  letter-spacing: var(--letter-spacing-display, -0.02em);
}
.prisma-view__actions {
  display: flex;
  gap: var(--space-2, 8px);
}
.prisma-view__diagram {
  display: flex;
  justify-content: center;
  padding: var(--space-4, 16px);
  background-color: white;
  border: 1px solid var(--color-border, #c7c4d8);
  border-radius: var(--radius-default, 0.25rem);
}
.prisma-view__summary {
  margin-top: var(--space-4, 16px);
  font-size: var(--font-size-caption, 13px);
  color: var(--color-on-surface-variant, #464555);
  text-align: center;
}
.prisma-view__reasons {
  margin-top: var(--space-6, 24px);
  border: 1px solid var(--color-border, #c7c4d8);
  border-radius: var(--radius-default, 0.25rem);
  padding: var(--space-4, 16px);
}
.prisma-view__reasons h2 {
  font-size: var(--font-size-h2, 16px);
  margin-bottom: var(--space-2, 8px);
}
.prisma-view__reasons ul {
  list-style: disc;
  padding-left: var(--space-4, 16px);
}
.prisma-view__reasons li {
  font-size: var(--font-size-caption, 13px);
  margin-bottom: var(--space-1, 4px);
}
.btn {
  padding: var(--space-2, 8px) var(--space-3, 12px);
  border-radius: var(--radius-default, 0.25rem);
  font-size: var(--font-size-caption, 13px);
  font-weight: var(--font-weight-semibold, 600);
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  gap: var(--space-1, 4px);
}
.btn__icon {
  font-size: 18px;
}
.btn--primary {
  background-color: var(--color-primary, #3525cd);
  color: var(--color-on-primary, #ffffff);
}
.btn--secondary {
  background-color: var(--color-surface-container-high, #eae6f4);
  color: var(--color-on-surface, #1b1b24);
}
.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>
